### ISSUE TITLE
Different Basic Auth credentials for every service

### ISSUE THREAD

**Issue by ericis** [joshiste/spring-boot-admin-samples#2]
Every service will have its own set of basic auth credentials (currently) as well as verifying a JSON Web Token (JWT) API Key (shared secret using public key asymmetric encryption).

Your Basic Auth example assumes a single, shared set of credentials.

I can probably implement a ZuulFilter along the same lines and simply sniff the URL to determine which key to use, but I thought I'd ask your opinion about how to handle?

**Comment by joshiste** [comment]
This problem is already solved with spring boot admin 1.5.x.
It allows the services to submit credentials to the admin using metadata. If you don't like this you can also implement your own `HttpHeaderProvider` to inject authorization headers to the requests....
